manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      # あなたがたった今作成した、確実に見つかるフォーク（コピー）を指定します！
      url: https://github.com/Decaocto/zmk-pmw3610-driver
      revision: main
    - name: zmk-rgbled-widget
      url: https://github.com/caksoylar/zmk-rgbled-widget
      revision: main
  self:
    path: config
